Fail hard when we can't figure out package manager
Instead of sliding through the whole script with install undefined,
print an error message and die.

diff --git a/buildprep b/buildprep
--- a/buildprep
+++ b/buildprep
@@ -55,7 +55,8 @@ then
     installer=yast
     install="$do $installer --install"
 else
-    installer=unknown
+    echo "# ERROR: Package manager unidentified - Unsupported operating system"
+    exit 1
 fi
 echo "# Your package installer is ${installer}."
 echo ""
