Cleanup uid != 0 check and error message in buildprep

diff --git a/buildprep b/buildprep
--- a/buildprep
+++ b/buildprep
@@ -36,16 +36,15 @@ done
 
 if [ "$DRYRUN" = "yes" ]
 then
-    do=echo
-    echo "# Run this without -n, as root, for actual installation.\n#"
+	do=echo
+	echo "# Run this without -n, as root, for actual installation.\n#"
 else
-    do=""
-fi
-
-if [ "$do" = "" -a `id -u` != 0 ]
-then
-    echo "#You must be running as root for your installer to do its thing."
-    exit 1
+	do=""
+	if [ "$(id -u)" != 0 ]
+	then
+		echo "# ERROR: You must be running as root for your installer to do its thing."
+		exit 1
+	fi
 fi
 
 if emerge --version 2>/dev/null
